baseURL = "https://qrxnz.dev"
title = "qrxnz's space"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "qrxnz"
    badge = "orange"
    quote = "red"
    # notice = "Hello, world. This is a notification."
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    logo = "/avater.png"
    bio = """
    <p> I am a cybersecurity enthusiast, primarily interested in web and hardware. I enjoy developing open source projects, treating it as a fun activity. In my free time, I mainly ride my skateboard and read books… 🛹 ^‿^ 📚 </p>
    <br />
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:send@qrxnz.dev"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/qrxnz/"
    name = "github"
    weight = 1
