baseurl = "https://qrxnz.dev"
languageCode = "en-us"
theme = "hugo-theme-stack"
title = "qrxnz's blog"
copyright = "qrxnz"
DefaultContentLanguage = "en"
hasCJKLanguage = false

[languages.en]
languageName = "English"
title = "qrxnz's blog"
weight = 1

[services.disqus]
shortname = "hugo-theme-stack"

[services.googleAnalytics]

[pagination]
pagerSize = 3

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "😺"
  subtitle = "I use keyboard BTW"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/qrxnz"

    [menu.social.params]
    icon = "brand-github"

  [[menu.social]]
  identifier = "mastodon"
  name = "Mastodon"
  url = "https://mastodon.social/@qrxnz"

    [menu.social.params]
    icon = "brand-mastodon"

  [[menu.social]]
  identifier = "linkedin"
  name = "Linkedin"
  url = "https://www.linkedin.com/in/karol-skoczyk17"

    [menu.social.params]
    icon = "brand-linkedin"

  [[menu.social]]
  identifier = "youtube"
  name = "Youtube"
  url = "https://www.youtube.com/@qrxnz9209/"

    [menu.social.params]
    icon = "brand-youtube"

  [[menu.social]]
  identifier = "linktree"
  name = "Linktree"
  url = "https://linktr.ee/qrxnz"

    [menu.social.params]
    icon = "brand-linktree"
  
[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
